M48
; DRILL file {KiCad 9.0.0} date 2025-03-12T20:24:54+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-12T20:24:54+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.900
%
G90
G05
T1
X163.0Y-105.0
T2
X148.65Y-112.0
X161.35Y-112.0
T3
X132.0Y-109.46
X132.0Y-112.0
M30
